"""add custom request view tracking and message image

Revision ID: 76e1a6c1267e
Revises: j0e1f2g3h4i5
Create Date: 2026-05-01 13:24:06.341511

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '76e1a6c1267e'
down_revision: str | Sequence[str] | None = 'j0e1f2g3h4i5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('custom_request_messages', sa.Column('image_url', sa.String(), nullable=True))
    # 既有 row 沒值 → server_default=0 讓 ALTER 順利通過，再 ORM 層的 default 接手新 row
    op.add_column(
        'custom_requests',
        sa.Column('view_count', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column(
        'custom_requests',
        sa.Column('last_viewed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_requests', 'last_viewed_at')
    op.drop_column('custom_requests', 'view_count')
    op.drop_column('custom_request_messages', 'image_url')
    # ### end Alembic commands ###
